apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: shubh9975/images:v1.2.6
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskdemo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: .
    repoURL: git@github.com:shubh9975/App-Manifest-.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=false
  hooks:
  - postSync:
      object:
        kind: Deployment
        name: flaskdemo
      command:
        - /bin/bash
        - -c
        - |
          ./post-sync-hook.sh

