apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: calsoft
          image: shubh9975/simple-app:v3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31488
  selector:
    app: helloworld
